### ISSUE TITLE
Общие замечания по проекту

### ISSUE THREAD

**Issue by Sergio-Ka** [SpekalsG3/HTMLPractice#1]
Проект по большей части не соответствует требованиям:
1. Не используется методология БЭМ
2. Верстка не является компонентной
3. Не используются препроцессоры

**Comment by SpekalsG3** [comment]
1. БЭМ использовался но немного неправильно. Исправлено.
2. Подключил Pug и настроил компонентную верстку. Исправлено.
3. Подключил и настроил SASS препроцессор. Исправлено.

**Comment by Sergio-Ka** [comment]
Не нужно самому закрывать замечания. Их закрывает либо тот кто выдал, либо ты сам если тебе кто-то из проверяющих говорит об этом явно.

**Comment by SpekalsG3** [comment]
Упс, не знал) Думал логичнее делать отдельные ишьюс

**Comment by Sergio-Ka** [comment]
Я не вижу компонентности верстки - не вижу компонентов, не вижу структуру директорий, которая намекает на компонентность и то что что компоненты сделаны в соответсвии С БЭМ и выделены каждый в свою папку и оформлены миксинами каждый. Не вижу файла README.md с описанием проекта и с командами которые нужны для установки и разворачивания проекта. Да и самого БЭМ в названии классов я тоже не вижу. И кроме того миксы у нас в отличии от оригинального БЭМ использовать нельзя кроме миксов модификаторов. Вопросы позиционирования решаются обертками, которые по сути элементы (по БЭМ) родительских блоков.

**Comment by SpekalsG3** [comment]
1. Все же понял, что такое БЭМ. Если текущая версия не правильная, то черт его знает, наверно нужен будет пример подобного сайта с использованием БЭМ. Также, видов БЭМ несколько, я же придерживался конструкции блок__элемент--модификатор. Исправлено.
2. Написал README.md но без излишков - только как запустить проект. Исправлено.
3. Пропустил пару пунктов в стандартах. Исправлено.
4. Реализовал компонентность. Была и раньше, но компоненты были расписаны в одном соответствующем файле. Исправлено.

**Comment by Sergio-Ka** [comment]
1. В readme указать явно команду на клонирование репы типа git clone "ТВОЙРЕПО". после простого копирования репозитория если сделать как написано в readme и запустить npm run dev ничего не происходит, потому что надо установить зависимости командой npm install, чего в readme не указано. Надо указать.
2. Чтобы собрать твой проект командой npm run dev у меня, судя по всему, тупо не хватает памяти, а у меня ее 12GB, и по некоторым данным виной тому код твоего проекта. Такого быть не должно.
![image](https://user-images.githubusercontent.com/33621369/64942435-37d4dd00-d893-11e9-96cf-00127d44c48e.png)
3. Я по прежнему не вижу сдвигов по организации структуры директорий с точки зрения БЭМ. У нас это в частности предполагает разбитие кода на компоненты (визуальные компоненты - например - кнопка, меню, профайл, дропдаун, календарь и т.д.), выделение каждого компонента в отдельную директорию имя которой совподает с именем компонента (то есть папка в которой лежат все реализации данного конкретного компонента на всех технологиях, то есть структура - html (pug), визуальное оформление css (stylus, scss, less) и картинки, логика - js (ts)). Само именование компонентов должно быть осмысленным. Компоненты  - это строительные блоки проекта, которые можно переиспользовать не только в проекте но и между проектами в том числе за счет модификаторов БЭМ меняя вид блоков. Структура проекта должна быть древовидной, то есть каждый компонент подключает последующий, если его использует, тот в свою очередь следующий и так далее. По организации директорий написано кстати на ru.bem.info - то есть на официальном сайте методологии. Нотацию мы используем вида "блок__элемент_модификатор", тебе нужно так же использовать ее, так как кодстайл в команде должен быть одинаковым. Всякие статичные файлы и все такое не выделяется как правило, ибо это в основном часть реализации какого-то компонента (который в свою очередь реализуется как блок по БЭМ). Кстати сами блоки по БЭМ (читай компоненты) должны быть реализованы миксинами pug (не путать с миксами БЭМ). То есть не какая-то повторяющаяся функциональность на более мелком уровне, которую ты выделяешь в миксины и используешь в проекте (что увеличивает связанность кода, что плохо в свою очередь), а конкретно сами блоки (компоненты - логически законченные самодостаточные единицы которые ты выделяешь визуально) и есть та самая функциональность которую ты выделяешь в виде миксинов и из которых строишь проект как из кирпичиков. Компоненты тут - как черные ящики - у них есть интерфейс (параметры) которые и принимает миксин, а в замен возвращает тебе вид (верстку). Сами параметры должны передаваться в миксин объектом, а не просто цифрами как обычно в функциях. Ибо объект позволяет тебе указывать не все параметры блока, позволяет не соблюдать их порядок, позволяет делать декомпозицию, позволяет назначать значения по умолчанию и даже валидировать их. Так должно выглядеть в идеале.
Сейчас же если посмотреть в структуру проекта в папку src, то там какое-то искусственное разделение и группировка файлов по технологиям из чего я делаю вывод, что смысл БЭМ и компонентности тебе не ясен. А дальше и можно не смотреть ибо основной скил не усвоен. Постарайся понять написанное, если не ясно формулируй кратко и четко и спрашивай если не ясно, буду пытаться прояснить. Вот статейка на тему компонентности кстати, если ты вдруг ее еще не видел https://fullstack-development.gitbook.io/learn/komponentnaya-arkhitektura
