### ISSUE TITLE
решить проблему со сборкой проекта

### ISSUE THREAD

**Issue by Sergio-Ka** [SpekalsG3/HTMLPractice#2]
Проект не собирается. Проблему нужно решить. И ее должен решать не клиент (представь что клиент в данном случае я), а исполнитель.
https://user-images.githubusercontent.com/33621369/64942435-37d4dd00-d893-11e9-96cf-00127d44c48e.png
Я немного посмотрел по причинам того что не собирается. Проблема в infragistics.core.js или infragistics.dv.js

**Comment by SpekalsG3** [comment]
Может сейчас запуститься? Понимаю, что это должен решать не клиент, но проблема скорее всего не в проекте, тк у меня как по маслу. У меня есть несколько вариантов:
1) У ноды есть лимит памяти, которую он может использовать, что изменяется командой 

> node --max-old-space-size=4096 yourFile.js

2) На диске, где установлена нода, не хватает места для запуска.

**Comment by Sergio-Ka** [comment]
Еще раз, проблема возникает в указанной выше библиотеке. Что делает данная библиотека и какая такая жесткая необходимость в этой библиотеке, если по ней так же есть и второе замечание?

**Comment by SpekalsG3** [comment]
Заменил в итоге библиотеку. Также теперь все загружается из node_modules, что тоже может повлиять. Если проблема была в ней, то запуститься, иначе надо будет дальше фиксить.

**Comment by Sergio-Ka** [comment]
Проект по прежгнему не собирается, но сейчас проблема в другом. Ты добавил новые шрифты:

![image](https://user-images.githubusercontent.com/33621369/66625494-984f0400-ec1e-11e9-8f7a-99cfbb8e8b7d.png)

но в css у тебя указаны другие шрифты, не те которые добавлены:

![image](https://user-images.githubusercontent.com/33621369/66625527-bfa5d100-ec1e-11e9-9014-5dfeb0389747.png)

**Comment by SpekalsG3** [comment]
Видимо слетело, когда разбирался с отменой и изменением коммитов. Исправил
