### ISSUE TITLE
Модули использовать из node_modules

### ISSUE THREAD

**Issue by Sergio-Ka** [SpekalsG3/HTMLPractice#3]
Сейчас происходит подключение сторонних библиотек, которые лежат в src/lib. Такого быть не должно. Все зависимости такого рода подключаются из node_modules (куда ставятся в свою очередь из npm) и заносятся в файл package.json. Такой подход гарантирует однообразие файлов используемых зависимостей, возможность разворачивания проектов на других машинах без лишних проблем, безопасность. Этот пункт описан в стандартах FSD. Соответственно и папка lib не нужна.

**Comment by SpekalsG3** [comment]
А что делать с плагинами, которые не устанавливаются через npm, а скачиваются?

**Comment by Sergio-Ka** [comment]
Плохой довод. Скорее всего ты что-то делаешь не так, а потом идешь по легкому пути - типа не работает и все на этом. А как ты работать собираешься, если проблемы такого рода на рабочем проекте возникнут? Ты хотя бы пробовал решить проблему, гуглил почему не работает? У остальных же работает как-то, никто файлы библиотек не льет в виде файлов.

**Comment by SpekalsG3** [comment]
Согласен, что-то я совсем поспешил, просто опыта до этого не было с нодой. Решил все же сделать для dropdown отдельный блок, но с тем же скриптом. Остальные же плагины и библиотеки перенесены в node_modules.
