### ISSUE TITLE
именование подключаемых файлов проекта

### ISSUE THREAD

**Issue by Sergio-Ka** [SpekalsG3/HTMLPractice#4]
Подключаемые файлы в проекте (да и вообще все) именовать в стиле lower-case-hyphenated если не указано иного, о чем написано в стандартах. Сейчас как минимум файлы в папках src/img и src/fonts не соответствуют этому правилу.

**Comment by SpekalsG3** [comment]
Исправил

**Comment by Sergio-Ka** [comment]
Именования файлов шрифтов у тебя по прежнему с большой буквы в репозитории. По умолчанию git не чувствителен к регистру, там надо настройку менять.

**Comment by SpekalsG3** [comment]
Понял. Исправил

**Comment by Sergio-Ka** [comment]
Исправления нужно делать коммитами, в коммитах указывать номер issue, которое правишь со знаком # (то есть для данного issue #4) - тогда коммиты будут появляться здесь в issue. Коммиты должны быть подробные (то есть 1 правка - 1 коммит) и иметь осмысленное название. Привыкай сразу работать с гитом нормально. По коммитам можно отслеживать твои правки сильно не углубляясь в проект и не тратя на них время. Как прочтешь это сообщение - можешь issue этот закрыть.
