### ISSUE TITLE
элементы БЭМ описывать в тех же файлах что и блоки

### ISSUE THREAD

**Issue by Sergio-Ka** [SpekalsG3/HTMLPractice#5]
Сейчас элементы выделены в отдельные папки например в компоненте form (и далее по проекту). Так делать не нужно ибо это избыточно. Возможно на большом проекте при сотне элементов одного блока, но здесь точно нет ибо усложняется структура директорий и это лишнее. Элементы описывать в тех же файлах что и блоки к которым эти элементы относятся.

**Comment by SpekalsG3** [comment]
Исправил
